        function openModal(element) {
            document.getElementById('myModal').style.display = "block";
            document.getElementById('modalImage').src = element.src;
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';
            document.body.style.overflow = 'hidden';

        }
        function closeModal() {
            document.getElementById('myModal').style.display = "none";
            document.body.style.overflow = 'auto';
        }